#!/bin/sh
set -eu

cd "$(dirname "$0")/.."

OUT_FILE=buf.gen.yaml
GO_OUT=api/gen/go
ES_OUT=web/src/gen
OPENAPI_OUT=api/gen/openapi
# Relative to OPENAPI_OUT. api/gen/openapi.go embeds the document under this name.
OPENAPI_DOC=todo/v1/todo.openapi.yaml

write=false
if [ $# -eq 1 ] && [ "$1" = "--out-dirs" ]; then
  printf '%s\n' "$GO_OUT" "$ES_OUT" "$OPENAPI_OUT"
  exit 0
elif [ $# -eq 1 ] && [ "$1" = "--write" ]; then
  write=true
elif [ $# -gt 0 ]; then
  printf 'usage: %s [--out-dirs|--write]\n' "$0" >&2
  exit 1
fi

go_mod_version() {
  version=$(sed -n "s|^[[:space:]]*$1[[:space:]]\{1,\}\(v[^[:space:]]*\).*|\1|p" api/go.mod | head -1)
  if [ -z "$version" ]; then
    printf '%s not found in api/go.mod\n' "$1" >&2
    exit 1
  fi
  printf '%s' "$version"
}

package_json_version() {
  version=$(sed -n "s|.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*|\1|p" web/package.json | head -1)
  if [ -z "$version" ]; then
    printf '%s not found in web/package.json\n' "$1" >&2
    exit 1
  fi
  # A range such as ^2.14.1 would become the plugin version v^2.14.1, which buf only
  # rejects much later with an error that says nothing about package.json.
  case "${version#v}" in
    [0-9]*.[0-9]*.[0-9]*) ;;
    *)
      printf '%s in web/package.json is not pinned to an exact version: %s\n' "$1" "$version" >&2
      exit 1
      ;;
  esac
  printf 'v%s' "${version#v}"
}

# Read straight from the Makefile rather than through an exported variable, so that
# the script also runs outside make (Renovate's post-upgrade task, docs/renovate.md).
makefile_version() {
  version=$(sed -n "s|^$1[[:space:]]*:=[[:space:]]*\(v[^[:space:]]*\).*|\1|p" Makefile | head -1)
  if [ -z "$version" ]; then
    printf '%s not found in Makefile\n' "$1" >&2
    exit 1
  fi
  printf '%s' "$version"
}

PROTOBUF_GO=$(go_mod_version google.golang.org/protobuf)
CONNECT_GO=$(go_mod_version connectrpc.com/connect)
BUFBUILD_ES=$(package_json_version @bufbuild/protobuf)
CONNECT_OPENAPI=$(makefile_version CONNECT_OPENAPI_VERSION)

render() {
  cat <<EOF
# Generated by scripts/gen-buf-config.sh. Do not edit.
# Plugin versions follow the runtime libraries in api/go.mod and web/package.json;
# connect-openapi's is pinned in the Makefile (see the comment there).
version: v2
clean: true
managed:
  enabled: true
  disable:
    # protovalidate ships its own published Go SDK; rewriting its go_package
    # would break the references to it.
    - file_option: go_package
      module: buf.build/bufbuild/protovalidate
    # Same for gnostic, whose annotations todo/v1/openapi.proto carries.
    - file_option: go_package
      module: buf.build/gnostic/gnostic
    # Same for googleapis, whose google.api.http annotations todo/v1/todo.proto
    # carries. The Go plugin generates no code for a dependency module, so the
    # rewritten path would name a package that is never written.
    - file_option: go_package
      module: buf.build/googleapis/googleapis
  override:
    - file_option: go_package_prefix
      value: example/app/gen/go
plugins:
  - remote: buf.build/protocolbuffers/go:$PROTOBUF_GO
    out: $GO_OUT
    opt: paths=source_relative
  - remote: buf.build/connectrpc/go:$CONNECT_GO
    out: $GO_OUT
    opt: paths=source_relative
  - remote: buf.build/bufbuild/es:$BUFBUILD_ES
    out: $ES_OUT
    opt: target=ts
    # The generated TS imports the descriptors of every proto dependency
    # (buf/validate) by a relative path, so those must be generated too.
    include_imports: true
  - remote: buf.build/community/sudorandom-connect-openapi:$CONNECT_OPENAPI
    out: $OPENAPI_OUT
    # One document for the whole API rather than the default of one per proto
    # file, which also spares the empty documents that the files declaring no
    # service would produce. todo/v1/openapi.proto names the result.
    opt: path=$OPENAPI_DOC
EOF
}

if [ "$write" = false ]; then
  render
  exit 0
fi
# Through a temporary file, so that a failure leaves the committed buf.gen.yaml
# intact rather than truncated.
render >"$OUT_FILE.tmp" || {
  rm -f "$OUT_FILE.tmp"
  exit 1
}
mv -f "$OUT_FILE.tmp" "$OUT_FILE"
