#!/bin/sh
set -eu

cd "$(dirname "$0")/.."

GO_OUT=api/gen/go
ES_OUT=web/src/gen
OPENAPI_OUT=api/gen/openapi

if [ "${1:-}" = "--out-dirs" ]; then
  printf '%s\n' "$GO_OUT" "$ES_OUT" "$OPENAPI_OUT"
  exit 0
fi
if [ $# -gt 0 ]; then
  printf 'usage: %s [--out-dirs]\n' "$0" >&2
  exit 1
fi

# Pinned in the Makefile, where Renovate can update it (docs/renovate.md).
CONNECT_OPENAPI="${CONNECT_OPENAPI_VERSION:?is not set; run this script through make (make gen)}"

go_mod_version() {
  version=$(sed -n "s|^[[:space:]]*$1[[:space:]]\{1,\}\(v[^[:space:]]*\).*|\1|p" api/go.mod | head -1)
  if [ -z "$version" ]; then
    printf '%s not found in api/go.mod\n' "$1" >&2
    exit 1
  fi
  printf '%s' "$version"
}

package_json_version() {
  version=$(sed -n "s|.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*|\1|p" web/package.json | head -1)
  if [ -z "$version" ]; then
    printf '%s not found in web/package.json\n' "$1" >&2
    exit 1
  fi
  printf 'v%s' "${version#v}"
}

PROTOBUF_GO=$(go_mod_version google.golang.org/protobuf)
CONNECT_GO=$(go_mod_version connectrpc.com/connect)
BUFBUILD_ES=$(package_json_version @bufbuild/protobuf)

cat <<EOF
# Generated by scripts/gen-buf-config.sh. Do not edit.
# Plugin versions follow the runtime libraries in api/go.mod and web/package.json;
# connect-openapi's is pinned in the Makefile (see the comment there).
version: v2
clean: true
managed:
  enabled: true
  disable:
    # protovalidate ships its own published Go SDK; rewriting its go_package
    # would break the references to it.
    - file_option: go_package
      module: buf.build/bufbuild/protovalidate
  override:
    - file_option: go_package_prefix
      value: example/app/gen/go
plugins:
  - remote: buf.build/protocolbuffers/go:$PROTOBUF_GO
    out: $GO_OUT
    opt: paths=source_relative
  - remote: buf.build/connectrpc/go:$CONNECT_GO
    out: $GO_OUT
    opt: paths=source_relative
  - remote: buf.build/bufbuild/es:$BUFBUILD_ES
    out: $ES_OUT
    opt: target=ts
    # The generated TS imports the descriptors of every proto dependency
    # (buf/validate) by a relative path, so those must be generated too.
    include_imports: true
  - remote: buf.build/community/sudorandom-connect-openapi:$CONNECT_OPENAPI
    out: $OPENAPI_OUT
EOF
